### ISSUE TITLE
How do we use this plugin to run certain programming language using same key?

### ISSUE THREAD

**Issue by sheetcoder** [lite-xl/console#9]
In my current IDE I have set **f5** for executing/compiling/running my programs in python (python file.py) and rust (cargo run). When I press **f5** depending on the file type on focus it should run or compile that program. How can I do the same thing with console. I am knew to lite-xl and lua.

**Comment by Guldoman** [comment]
Starting from the example in the README:
```lua
local core = require "core"
local command = require "core.command"
local keymap = require "core.keymap"
local console = require "plugins.console"

command.add("core.docview", {
  ["project:build-project"] = function()
    core.log "Building..."
    local build_command
    if string.match(core.active_view.doc.filename, "%.lua$") then
      build_command = "./build_lua.sh"
    elseif string.match(core.active_view.doc.filename, "%.c$") then
      build_command = "./build_c.sh"
    else
      return
    end
    console.run {
      command = build_command,
      file_pattern = "(.*):(%d+):(%d+): (.*)$",
      cwd = ".",
      on_complete = function(retcode) core.log("Build complete with return code "..retcode) end,
    }
  end
})

keymap.add { ["ctrl+b"] = "project:build-project" }
```
this will run `build_lua.sh` if you're currently in a Lua file, or `build_c.sh` if you're in a C file.

**Comment by sheetcoder** [comment]
@Guldoman Consider this scenario, lets say I have a folder called "Project" and in that folder I have multiple python files **file1.py**, **file2.py**,.....**file10.py** How do I write a **_general_** build script such that when lite-xl focus **file1.py** it should only run that python script (ctrl+b) and if I change my focus to **file3.py** and run (ctrl+b) it should only run that python script.

**Comment by Guldoman** [comment]
Starting from the example I provided, add a new `string.match` condition that matches python files and set the `build_command` variable like this:
```lua
build_command = string.format("python %q", core.active_view.doc.abs_filename)
```
This will run `python /path/to/current_file.py`.

**Comment by sheetcoder** [comment]
it worked and thank you for helping me. A suggestion if possible can you edit the readme to include this information as well, for noobs like me this is much more simpler.


```
local core = require "core"
local command = require "core.command"
local keymap = require "core.keymap"
local console = require "plugins.console"

command.add("core.docview", {
  ["project:build-project"] = function()
    core.log "Building..."
    local build_command
    if string.match(core.active_view.doc.filename, "%.py$") then
      build_command = string.format("python %q", core.active_view.doc.abs_filename)
    elseif string.match(core.active_view.doc.filename, "%.c$") then
      build_command = "./build_c.sh"
    elseif string.match(core.active_view.doc.filename, "%.lua$") then
      build_command = "./build_lua.sh"
    else
      return
    end
    console.run {
      command = build_command,
      file_pattern = "(.*):(%d+):(%d+): (.*)$",
      cwd = ".",
      on_complete = function(retcode) core.log("Build complete with return code "..retcode) end,
    }
  end
})

```
keymap.add { ["ctrl+b"] = "project:build-project" }
